name: Generate Album Markdown

on:
  issues:
    types: [opened, reopened]

jobs:
  generate_album_markdown:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.title }} =~ "https://adobe.ly"
    steps:
      - uses: actions/checkout@v3

      - id: import
        uses: abstrctn/lightroom-album-import@v0.1.0
        with:
          album_url: "${{ github.event.issue.title }}"
          download_directory: "images/live/$album_name"

      # Update ownership of downloaded files to current user
      - run: sudo chown -R $USER images/live/

      - name: Install dependencies
        run: sudo apt-get -qq install -y jq libimage-exiftool-perl
      - name: Generate markdown for album
        run: ./generate-markdown.sh "${{ steps.import.outputs.album_name }}"
        env:
          SORTED_IMAGE_PATHS: "${{ steps.import.outputs.sorted_image_paths }}"

      # The repo's Actions permissions > Workflow permissions must be set
      # to "Read and write" with the ability for Actions to create PRs
      # enabled.
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "Update album data for ${{ steps.import.outputs.album_name }}"
          branch: album/${{ steps.import.outputs.album_name }}
          title: "Import ${{ steps.import.outputs.album_name }}"
          body: |
            Imported album data from ${{ steps.import.outputs.album_name }}.

            Closes #${{ github.event.issue.number }}.