name: Generate Album Markdown

on:
  issues:
    types: [opened, reopened]

jobs:
  generate_album_markdown:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.title }} =~ "https://adobe.ly"
    steps:
      - uses: actions/checkout@v3

      - id: import
        uses: abstrctn/lightroom-album-import@v0.1.0
        with:
          album_url: "${{ github.event.issue.title }}"
          download_directory: "images/live/$album_name"

      - name: Install dependencies
        run: sudo apt-get -qq install -y jq libimage-exiftool-perl
      - name: Generate markdown for album
        run: ./generate-markdown.sh "${{ steps.import.outputs.album_name }}"
        env:
          SORTED_IMAGE_PATHS: "${{ steps.import.outputs.sorted_image_paths }}"

      - name: add-and-commit
        uses: EndBug/add-and-commit@v9
        with:
          new_branch: "album/${{ steps.import.outputs.album_name }}"
          # The repo's Actions permissions > Workflow permissions must be set
          # to "Read and write" with the ability for Actions to create PRs
          # enabled.
          default_author: github_actions

      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "album/${{ steps.import.outputs.album_name }}"
          destination_branch: main
          pr_title: "Import album ${{ steps.import.outputs.album_name }}"
          pr_body: |
            Added images from ${{ steps.import.outputs.album_name }} in Lightroom.

            Closes #${{ github.event.issue.number }}.