name: Import lightroom album

on:
  issues:
    types: [opened, reopened]

jobs:
  import_album:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.title }} =~ "https://adobe.ly"
    steps:
      - uses: actions/checkout@v3
      - id: import
        uses: abstrctn/lightroom-album-import@v0.1.0
        with:
          album_url: "${{ github.event.issue.title }}"

      # Update ownership of downloaded files to current user
      - run: sudo chown -R $USER *.jpg

      # The repo's Actions permissions > Workflow permissions must be set
      # to "Read and write" with the ability for Actions to create PRs
      # enabled.
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "Update album data for ${{ steps.import.outputs.album_name }}"
          branch: album/${{ steps.import.outputs.album_name }}
          title: "Import ${{ steps.import.outputs.album_name }}"
          body: |
            Imported album data from ${{ steps.import.outputs.album_name }}.

            Closes #${{ github.event.issue.number }}.